routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GuestController;
use App\Http\Controllers\PostingController;
use App\Http\Controllers\GambarController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [GuestController::class,'index']);
Route::get('tentang',[GuestController::class,'tentang']);
Route::get('/berita',[GuestController::class,'berita'])->name('berita');
Route::get('/singleberita/{id}',[GuestController::class,'singleberita'])->name('singleberita');
Route::get('/gallery',[GuestController::class,'gallery']);
Route::middleware(['auth:sanctum', 'verified'])->group(function(){

    Route::get('/dashboard', [DashboardController::class,'index'])->name('dashboard');
    Route::resource('/posting', PostingController::class);
    Route::resource('/gambar',GambarController::class);
    Route::get('/admin/tentang',[PostingController::class,'tentang'])->name('admin.tentang');
    Route::POST('/admin/tentang',[PostingController::class,'addtentang'])->name('addtentang');
});

app/Models/gambar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class gambar extends Model
{
    use HasFactory;
    protected $table = 'gambars';
    protected $primaryKey = "gambar_id";

    public function posting()
    {
        return $this->belongsTo('App\Models\posting', 'id_posting', 'posting_id');
    }


}

app/Http/Controllers/GambarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\posting;
use App\Models\gambar;
use Image;

class GambarController extends Controller
{
    public function index()
    {
        //$data = gambar::groupBy('category')->select('category',\DB::raw('count(*) as total'))->get();
        $data = gambar::orderBy('created_at','DESC')->get();

        return view('gambar.index')
        ->with('data',$data)
        ;
    }

    public function create()
    {

        return view('gambar.create');
    }
    public function store(Request $request)
    {
        \Validator::make($request->all(),[
            'gambar' => 'required | mimes : jpg,png,jpeg | max : 20000',

        ])->setAttributeNames([
            'gambar' => 'Gambar',

        ])->validate();



                $item = new gambar();
                //
                $extension = $request->gambar->extension();
               // $request->file('thumbnail')->storeAs('/upload/posting/thumbnail/', time().".".$extension);
               $thumbnail = time().".".$extension;

                $path = '/upload/posting/images/';
                $item->directory = '/upload/posting/images/'. $thumbnail;

                $request->gambar->move(public_path($path),$thumbnail);

                $item->nama = $thumbnail;
                $item->category = 'galery';
                $item->landing = 1;
                $item->save();
              //file_put_contents($path, $request->file('thumbnail'));


        session()->flash('success', 'Gambar Ditambahkan');
        return redirect()->back();
    }

    public function destroy($id,Request $request)
    {

        $item = gambar::find($id);
        $item->delete();
        \File::delete(public_path($item->directory));
        session()->flash('success', 'Gambar Dihapus');
        return redirect()->back();

    }

}

resources/views/gambar/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="page-title-box">
        <div class="page-title-right">

        </div>
        <h4 class="page-title">Gambar</h4>
    </div>
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Gambar</h4>
                <form action="{{route('gambar.store')}}" method="post" enctype="multipart/form-data">
                    @csrf


                    <div class="fallback form-group @if ($errors->has('gambar')) has-error @endif">
                        <input name="gambar" class="form-control-file" type="file" />
                        @if ($errors->has('gambar'))
                                <span class="help-block">
                                     <strong style="color:red;" class="red">{{ $errors->first('gambar') }}</strong>
                                </span>
                            @endif
                    </div>




                <!-- Preview -->
                <div class="dropzone-previews mt-3" id="file-previews"></div>
                <div class="form-group">
                    <button class="btn btn-pink">Simpan</button>
                </div>

            </form>

            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div><!-- end col -->
</div>
@endsection
@push('css')
<link href="{{asset('assets/libs/dropzone/min/dropzone.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/libs/dropify/css/dropify.min.css')}}" rel="stylesheet" type="text/css" />
@endpush
@push('scripts')
<script src="{{asset('assets/libs/dropzone/min/dropzone.min.js')}}"></script>
<script src="{{asset('assets/libs/dropify/js/dropify.min.js')}}"></script>
<!--<script src="{{asset('assets/js/pages/form-fileuploads.init.js')}}"></script>-->
@endpush
@push('docred')
Dropzone.options.dropzoneForm = {
    autoProcessQueue : false,
    acceptedFiles : ".png,.jpg,.gif,.bmp,.jpeg",

    init:function(){
      var submitButton = document.querySelector("#submit-all");
      myDropzone = this;

      submitButton.addEventListener('click', function(){
        myDropzone.processQueue();
      });

      this.on("complete", function(){
        if(this.getQueuedFiles().length == 0 && this.getUploadingFiles().length == 0)
        {
          var _this = this;
          _this.removeAllFiles();
        }
        load_images();
      });

    }

  };

  load_images();

  function load_images()
  {
    $.ajax({
      url:"{{ route('gambar.store') }}",
      success:function(data)
      {
        $('#uploaded_image').html(data);
      }
    })
  }

 

@endpush

resources/views/gambar/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="page-title-box">
        <div class="page-title-right">

        </div>
        <h4 class="page-title">Dashboard</h4>
    </div>
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Dropzone File Upload</h4>
                <form action="{{route('gambar.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                <p class="sub-header font-13">
                    DropzoneJS is an open source library that provides drag’n’drop file uploads with image previews.
                </p>


                    <div class="fallback form-group">
                        <input name="gambar" class="form-control-file" type="file" multiple />
                    </div>




                <!-- Preview -->
                <div class="dropzone-previews mt-3" id="file-previews"></div>
                <div class="form-group">
                    <button class="btn btn-pink">Simpan</button>
                </div>

            </form>

            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div><!-- end col -->
</div>
@endsection
@push('css')
<link href="{{asset('assets/libs/dropzone/min/dropzone.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/libs/dropify/css/dropify.min.css')}}" rel="stylesheet" type="text/css" />
@endpush
@push('scripts')
<script src="{{asset('assets/libs/dropzone/min/dropzone.min.js')}}"></script>
<script src="{{asset('assets/libs/dropify/js/dropify.min.js')}}"></script>
<!--<script src="{{asset('assets/js/pages/form-fileuploads.init.js')}}"></script>-->
@endpush
@push('docred')
Dropzone.options.dropzoneForm = {
    autoProcessQueue : false,
    acceptedFiles : ".png,.jpg,.gif,.bmp,.jpeg",

    init:function(){
      var submitButton = document.querySelector("#submit-all");
      myDropzone = this;

      submitButton.addEventListener('click', function(){
        myDropzone.processQueue();
      });

      this.on("complete", function(){
        if(this.getQueuedFiles().length == 0 && this.getUploadingFiles().length == 0)
        {
          var _this = this;
          _this.removeAllFiles();
        }
        load_images();
      });

    }

  };

  load_images();

  function load_images()
  {
    $.ajax({
      url:"{{ route('gambar.store') }}",
      success:function(data)
      {
        $('#uploaded_image').html(data);
      }
    })
  }

  $(document).on('click', '.remove_image', function(){
    var name = $(this).attr('id');
    $.ajax({
      url:"#",
      data:{name : name},
      success:function(data){
        load_images();
      }
    })
  });
@endpush

resources/views/gambar/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">

                </div>
                <h4 class="page-title">Dashboard</h4>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Data Gambar</h4>
                <div class="form-group"><a href="{{route('gambar.create')}}" class="btn btn-info">Tambah Gambar</a>
                    <table id="basic-datatable" class="table dt-responsive nowrap w-100">
                        <thead>
                            <tr>
                                <th>Status</th>
                                <th>Gambar</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                         <tbody>
                        @foreach ($data as $item)
                            <tr>
                                <td></td>
                                <td><img src="{{asset($item->directory)}}" width="144" height="96"></td>
                            <td><form class="pull-left" action="{{route('gambar.destroy',$item->gambar_id)}}" method="POST">@csrf <input type="hidden" name="_method" value="delete" /><button type="submit"   class="btn btn-danger" >Delete</button></td></form>
                            </tr>
                        @endforeach
                     </tbody>
                    </table>

    </div>
@endsection

@push('css')
    <link href="{{asset('assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css?v=0.00000001')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css?v=0.00000001')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css?v=0.00000001')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/libs/datatables.net-select-bs4/css/select.bootstrap4.min.css?v=0.00000001')}}" rel="stylesheet" type="text/css" />

@endpush
@push('scripts')
<!-- third party js -->
        <script src="{{asset('assets/libs/datatables.net/js/jquery.dataTables.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
        <script src="{{asset('assets/libs/datatables.net-select/js/dataTables.select.min.js')}}"></script>
        <script src="{{asset('assets/libs/pdfmake/build/pdfmake.min.js')}}"></script>
        <script src="{{asset('assets/libs/pdfmake/build/vfs_fonts.js')}}"></script>

        <!-- third party js ends -->
   <!--<script src="{{asset('assets-guest/js/pages/datatables.init.js')}}"></script>-->
   <script src="{{asset('assets/libs/sweetalert2/sweetalert2.min.js')}}"></script>
   <script src="{{asset('assets/js/pages/sweet-alerts.init.js')}}"></script>

        <!-- Sweet alert init js-->



@endpush

@push('docred')
   $("#basic-datatable").DataTable({
        language: {
            paginate: {
                previous: "<i class='mdi mdi-chevron-left'>",
                next: "<i class='mdi mdi-chevron-right'>"
            }
        },
        drawCallback: function() {
            $(".dataTables_paginate > .pagination").addClass("pagination-rounded")
        }
    });
$(".warning").click(function() {
            var id = $(this).data("value");
            var token = $(this).data("token");
            $.ajax(
            {
            url: " /gambar/"+id,
                type: 'PUT',
                dataType: "JSON",
                data: {
                    "id": id,
                    "_method": 'DELETE',
                    "_token": {{ csrf_token() }},
                },
                success: function ()
                {
                    console.log("it Work");
                },
                error: function()
                {
                    console.log("it doesn't Work");
                }
            });

            console.log("It failed");
        });

@endpush