routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GuestController;
use App\Http\Controllers\PostingController;
use App\Http\Controllers\GambarController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [GuestController::class,'index']);
Route::get('tentang',[GuestController::class,'tentang']);
Route::get('/berita',[GuestController::class,'berita'])->name('berita');
Route::get('/singleberita/{id}',[GuestController::class,'singleberita'])->name('singleberita');
Route::get('/gallery',[GuestController::class,'gallery']);
Route::middleware(['auth:sanctum', 'verified'])->group(function(){

    Route::get('/dashboard', [DashboardController::class,'index'])->name('dashboard');
    Route::resource('/posting', PostingController::class);
    Route::resource('/gambar',GambarController::class);
    Route::get('/admin/tentang',[PostingController::class,'tentang'])->name('admin.tentang');
    Route::POST('/admin/tentang',[PostingController::class,'addtentang'])->name('addtentang');
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

        <meta charset="utf-8" />
        <title>Dashboard | Dukuh Buahan</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{{asset('assets/images/favicon.ico')}}">

        <!-- Plugins css -->
        <link href="{{asset('assets/libs/flatpickr/flatpickr.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/libs/selectize/css/selectize.bootstrap3.css')}}" rel="stylesheet" type="text/css" />

        <!-- App css -->
        <link href="{{asset('assets/css/bootstrap-modern.min.css')}}" rel="stylesheet" type="text/css" id="bs-default-stylesheet" />
        <link href="{{asset('assets/css/app-modern.min.css')}}" rel="stylesheet" type="text/css" id="app-default-stylesheet" />

        <!-- icons -->
        <link href="{{asset('assets/css/icons.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('css/toastr.css')}}" rel="stylesheet" type="text/css" />

        @stack('css')
        <style>
            .has-error input[type=text]{
                border-color :  #f35d5d;
                color : #f35d5d;
            }
            .has-error input[type=file]{
                color : #f35d5d;
            }
             .has-error textarea{
                border-color : 1px solid #f35d5d;
                color : #f35d5d;
            }
        </style>
    </head>

    <body class="loading" data-layout-mode="detached" data-layout='{"mode": "light", "width": "fluid", "menuPosition": "fixed", "sidebar": { "color": "light", "size": "default", "showuser": true}, "topbar": {"color": "dark"}, "showRightSidebarOnPageLoad": true}'>

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Topbar Start -->
            <div class="navbar-custom">
                <div class="container-fluid">
                    <ul class="list-unstyled topnav-menu float-right mb-0">

                        <li class="dropdown notification-list topbar-dropdown">
                            <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">

                                <span class="pro-user-name ml-1">
                                    Admin <i class="mdi mdi-chevron-down"></i>
                                </span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                                <!-- item-->
                                <div class="dropdown-header noti-title">
                                    <h6 class="text-overflow m-0">Welcome !</h6>
                                </div>
                                                                <!-- item-->

                                    <form method="POST" action="{{ route('logout') }}">
                                        @csrf

                                        <x-jet-dropdown-link class="dropdown-item notify-item" href="{{ route('logout') }}"
                                                            onclick="event.preventDefault();
                                                                        this.closest('form').submit();">
                                            {{ __('Logout') }}
                                        </x-jet-dropdown-link>
                                    </form>


                            </div>
                        </li>


                    </ul>

                    <!-- LOGO -->
                    <div class="logo-box">
                        <a href="index-2.html" class="logo logo-dark text-center">
                            <span class="logo-sm">
                                <img src="../assets/images/logo-sm.png" alt="" height="22">
                                <!-- <span class="logo-lg-text-light">UBold</span> -->
                            </span>
                            <span class="logo-lg">
                                <img src="../assets/images/logo-dark.png" alt="" height="20">
                                <!-- <span class="logo-lg-text-light">U</span> -->
                            </span>
                        </a>

                        <a href="index-2.html" class="logo logo-light text-center">
                            <span class="logo-sm">
                                <img src="../assets/images/logo-sm.png" alt="" height="22">
                            </span>
                            <span class="logo-lg">
                                <img src="../assets/images/logo-light.png" alt="" height="20">
                            </span>
                        </a>
                    </div>

                    <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
                        <li>
                            <button class="button-menu-mobile waves-effect waves-light">
                                <i class="fe-menu"></i>
                            </button>
                        </li>

                        <li>
                            <!-- Mobile menu toggle (Horizontal Layout)-->
                            <a class="navbar-toggle nav-link" data-toggle="collapse" data-target="#topnav-menu-content">
                                <div class="lines">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </div>
                            </a>
                            <!-- End mobile menu toggle-->
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>
            <!-- end Topbar -->

            <!-- ========== Left Sidebar Start ========== -->
            <div class="left-side-menu">

                <div class="h-100" data-simplebar>

                    <!-- User box -->
                    <div class="user-box text-center">


                        <div class="dropdown">
                            <a href="javascript: void(0);" class="text-dark font-weight-normal dropdown-toggle h5 mt-2 mb-1 d-block"
                                data-toggle="dropdown">Admin</a>
                            <div class="dropdown-menu user-pro-dropdown">

                                <!-- item-->
                                <a href="javascript:void(0);" class="dropdown-item notify-item">
                                    <i class="fe-user mr-1"></i>
                                    <span>My Account</span>
                                </a>

                                <!-- item-->
                                <a href="javascript:void(0);" class="dropdown-item notify-item">
                                    <i class="fe-settings mr-1"></i>
                                    <span>Settings</span>
                                </a>

                                <!-- item-->
                                <a href="javascript:void(0);" class="dropdown-item notify-item">
                                    <i class="fe-lock mr-1"></i>
                                    <span>Lock Screen</span>
                                </a>

                                <!-- item-->
                                <a href="javascript:void(0);" class="dropdown-item notify-item">
                                    <i class="fe-log-out mr-1"></i>
                                    <span>Logout</span>
                                </a>

                            </div>
                        </div>
                        <p class="text-muted">Admin Head</p>
                    </div>

                    <!--- Sidemenu -->
                    <div id="sidebar-menu">

                        <ul id="side-menu">

                            <li class="menu-title">Navigation</li>

                            <li>
                            <a href="{{route('dashboard')}}" >


                                    <span> Dashboards </span>
                                </a>
                            </li>
                            <li>
                            <a href="{{route('posting.index')}}">


                                    <span> Berita </span>
                                </a>
                            </li>
                            <li>
                            <a href="{{route('gambar.index')}}" >

                                <span> Gallery </span>
                            </a>

                        </li>
                        <li>
                            <a href="{{route('admin.tentang')}}" >

                                <span> Tentang Dukuh </span>
                            </a>

                        </li>
                        </ul>

                    </div>
                    <!-- End Sidebar -->

                    <div class="clearfix"></div>

                </div>
                <!-- Sidebar -left -->

            </div>

            <div class="content-page">
                <div class="content">
                    <!-- Start Content-->
                    <div class="container-fluid">
                        @yield('content')
                    </div>
                </div>
            </div>
        </div>
        <!-- END wrapper -->
  <!-- Vendor js -->
  <script src="{{asset('assets/js/vendor.min.js')}}"></script>

  <!-- Plugins js-->
  <script src="{{asset('assets/libs/flatpickr/flatpickr.min.js')}}"></script>
  <script src="{{asset('assets/libs/apexcharts/apexcharts.min.js')}}"></script>

  <script src="{{asset('assets/libs/selectize/js/standalone/selectize.min.js')}}"></script>

  <!-- Dashboar 1 init js-->
  <script src="{{asset('assets/js/pages/dashboard-1.init.js')}}"></script>

  <!-- App js-->
  <script src="{{asset('assets/js/app.min.js')}}"></script>
  <script src="{{asset('js/toastr.min.js')}}"></script>
  @stack('scripts')
    <script>
        $(document).ready(function(){
            @stack('docred')
            @foreach (['error', 'success', 'info'] as $msg)
                    @if(Session::has($msg))
                    toastr.options = Object.assign({}, toastr.options, {
                closeButton: true
            });
            toastr.{{$msg}}('{{session($msg)}}','{{strtoupper($msg)}}');
            @endif
        @endforeach
        })
    </script>
</body>


</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        @livewireStyles

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.js" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-dropdown')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">
        <!-- Styles -->
        <link rel="stylesheet" href="{{asset('css/app.css') }}">
        
         
        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.0/dist/alpine.js" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/landing.blade.php
<!DOCTYPE html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Dukuh Buahan') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{asset('asset-guest/sass/app.css?v=00.00006')}}">
        <link rel="stylesheet" href="{{asset('assets-guest/css/flaticon.css')}}">
        <link rel="stylesheet" href="{{asset('assets-guest/css/font-awesome.min.css')}}">
        <!-- Favicon -->
        <link rel="apple-touch-icon" sizes="180x180" href="{{asset('assets-guest/images/favicon/apple-touch-icon.png')}}">
        <link rel="icon" type="image/png" href="{{asset('assets-guest/images/favicon/favicon-32x32.png')}}" sizes="32x32">
        <link rel="icon" type="image/png" href="{{asset('assets/images/favicon/favicon-16x16.png')}}" sizes="16x16">
        <style>
            .page-item.active .page-link{
                background-color:#fb7162 !important;
                border-color:#fb7062 !important;
                color:#fff !important;
            }
            .page-link{
                color:#fb7062 !important;
            }
            .header-title{
                color: #fff;
                font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
                font-size: 20px;
                padding: 17px 0 0 0;
            }
        </style>
        @stack('css')
        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.js" defer></script>
    </head>
    <body>
        <div class="boxed_wrapper">
            <header class="main-header header-style-four">
                <!--Start header lawer -->
                <div class="row">
                <div class="container">

                        <div class="container-fluid">
                        <div class="col-3 m-0 pull-left">
                            <!--<img src="#" alt="font awesome" class="img">-->
                            <h1 class="header-title">Dukuh Buahan</h1>
                        </div>
                        <div class="col-9 pull-right">


                            <!--Top Left-->
                            <div class="header-lawer-left-style4 float-right">
                                <div class="nav-outer clearfix">
                                    <!--Mobile Navigation Toggler-->
                                    <div class="mobile-nav-toggler">
                                        <div class="inner">
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </div>
                                    </div>
                                    <!-- Main Menu -->
                                    <nav class="main-menu style4 navbar-expand-md navbar-light">
                                        <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                                            <ul class="navigation clearfix">
                                               <!-- <li class="current">
                                                    <a class="home-icon" href="#">Beranda</a>
                                                </li>-->
                                            <li class="current"><a href="{{route('berita')}}">Berita</a></li>
                                               <!-- <li><a href="#">Galery</a></li>
                                                <li><a href="#">Tentang Dukuh</a></li>-->
                                            </ul>
                                        </div>
                                    </nav>
                                    <!-- Main Menu End-->
                                </div>
                            </div>

                            </div>
                        </div>

                        </div>

                </div>
                <!--End header lawer -->

                <!--Sticky Header-->
                <div class="sticky-header white-bg">

                </div>
                <!--End Sticky Header-->



                <!-- Mobile Menu  -->
                <div class="mobile-menu">
                    <div class="menu-backdrop"></div>
                    <div class="close-btn"><span class="icon flaticon-multiply"></span></div>

                    <nav class="menu-box">
                        <div class="nav-logo"><a href="index.html"><img src="assets/images/resources/logo-7.png" alt="" title=""></a></div>
                        <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
                    </nav>
                </div>
                <!-- End Mobile Menu -->

            </header>
            @yield('content')
            </div>
        </div>
        <footer class="footer-area style4">
            <div class="footer">
                <div class="container">
                    <div class="row">
                        <!--Start single footer widget-->
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 wow animated fadeInUp" data-wow-delay="0.3s">
                            <div class="single-footer-widget marbtm50">
                                <div class="our-company-info">
                                    <div class="footer-logo">
                                        <h2>Dukuh Buahan</h2>
                                    </div>
                                    <div class="text">
                                        <p>Website Dukuh Buahan</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--End single footer widget-->

                    </div>
                </div>
            </div>
        </footer>
    </body>
    <script src="{{asset('assets-guest/js/jquery.js')}}"></script>
    <script src="{{asset('assets-guest/js/aos.js')}}"></script>
    <script src="{{asset('assets-guest/js/appear.js')}}"></script>
    <script src="{{asset('assets-guest/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('assets-guest/js/bootstrap-select.min.js')}}"></script>
    <script src="{{asset('assets-guest/js/isotope.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.bootstrap-touchspin.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.countdown.min.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.countTo.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.easing.min.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.enllax.min.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.fancybox.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.mixitup.min.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.paroller.min.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.polyglot.language.switcher.js')}}"></script>
    <script src="{{asset('assets-guest/js/map-script.js')}}"></script>
    <script src="{{asset('assets-guest/js/nouislider.js')}}"></script>
    <script src="{{asset('assets-guest/js/owl.js')}}"></script>
    <script src="{{asset('assets-guest/js/validation.js')}}"></script>
    <script src="{{asset('assets-guest/js/wow.js')}}"></script>
    <script src="{{asset('assets-guest/js/jquery.magnific-popup.min.js')}}"></script>
    <script src="{{asset('assets-guest/js/slick.js')}}"></script>
    <script src="{{asset('assets-guest/js/lazyload.js')}}"></script>
    <script src="{{asset('assets-guest/js/scrollbar.js')}}"></script>

    <!-- thm custom script -->
    <script src="{{asset('assets-guest/js/custom.js')}}"></script>
    @stack('scripts')
    <script>
        $( document ).ready(function() {
            @stack('docred')
        });
    </script>

</html>